Hashtag
tomohiko9090/STECH_Community pull request #3
Opened 2021-02-17 12:00 UTC by hibiki0612

2021-02-17 12:07 UTC, K-out-A requested changes
データベースを消してください。

2021-02-17 12:11 UTC, hibiki0612 commented on static/hashtag_list.css
> +  background: url(https://s3-us-west-2.amazonaws.com/s.cdpn.io/85188/bg-red.jpg);
少し変更してからコミットします

2021-02-17 12:14 UTC, K-out-A commented on templates/hashtag/hashtag.html
> +{% block customcss %}<!--cssを個別に呼び出したい時に使う-->
```suggestion
{% block customcss %}
```

2021-02-22 11:28 UTC, closed without merging

2021-02-22 11:28 UTC, hibiki0612 commented
test